= NOTICE of Packaged Dependencies
:page-permalink: {site_path}/notice

The following open source packages are fully or partially included with ACMEdoc.

include::{includes_path}/built/dependencies_table.adoc[]


[[notice-sourcing]]
.How this appendix is sourced
****
This file is not sourced as YAML but rather as plain text for a couple of reasons.
First of all, this file is traditionally named `NOTICE` and kept prominently in the root directory in open-source projects.

More importantly, since this file _must_ be present in this open-source project where it is distributed (GitHub), we do not want to duplicate the source.
So we store it in a very human-readable plaintext format, then we extract data from it during the parsing step of the build routine.

Here is the NOTICE file in its entirety:

[source,plaintext]
.ACMEdoc NOTICE file
----
include::{root_path}/NOTICE[]
----

And here is the section from `_configs/build-docs.yml` that instructs the data extraction:

[source,yaml]
.From build-docs.yml
----
include::{root_path}/_configs/build-docs.yml[tags=regex-notice]
----
****
