= {portal_product} {portal_user} {portal_term}
// Bump header levels for all subsequent includes
:page-permalink: '{site_path}/home'
:leveloffset: +1
:copyright_line: Copyright (C) 2018 {company_name}
:toc: macro
:page-topnav: topnav

// for book-formatted, include the copyright and TOC
ifdef::pdf[]

toc::[]

{copyright_line}

TIP: You are seeing a TOC and copyright line above because this is the PDF/book edition.
endif::[]

// include intro text common to all portals
include::includes/intro_portal_common.adoc[]

[TIP]
--
The content above appears in all editions, but some of it is variable.
Many of the strings (e.g., _{portal_product}_ and even _{user_verb}_, etc) are variables (`\{portal_product}` and `\{user_verb}`) are dynamically substituted with AsciiDoc attributes at build time.
The content is included from a common file, like so:

[source,asciidoc]
 include::includes/intro_portal_common.adoc[]
--

// include intro text specific to current portal
include::includes/intro_portal_{portal_slug}.adoc[]

[TIP]
--
The above text is from by a dynamically included file using:

[source,asciidoc]
 include::portal/intro_portal_{portal_slug}.adoc[]

Where `\{portal_slug}` is a variable defined in a block of a YAML file (`_configs/portals.yml`) that is only passed to one designated portal during the build config file (`_configs/build-docs.yml`), designated in the build config file as `data: _data/portals.yml:portal-{portal_id}`.
--

// insert 'jargon ahead' warning
include::includes/snippets.adoc[jargon-warning]

// for non-PDF, include the copyright line here
ifndef::pdf[{copyright_line}]

// for book-formatted output, include the remainder of the portal's contents in this document

ifdef::pdf[]

include::pages/product-overview.adoc[]

include::pages/framework-structure.adoc[]

[appendix]
[[jargon_guide]]
include::topics/jargon-guide.adoc[]

endif::pdf[]
